modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="more_things_mod"
version="1.0.0"
displayName="More Things Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="terry, MCreator"

[[dependencies.more_things_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




